adobe/helix-rum-bundler

- .github/workflows/main.yaml
Please ensure your pull request adheres to the following guidelines:
Thanks for contributing!
> chore: testing config

- src/api/bundles.js
- src/support/PathInfo.js
- test/dev/tools/import-bundles.js
- test/dev/tools/util.js
- add surrogate-key header for /bundles route
- mask user agent in importer tool
> various changes

- .github/workflows/main.yaml
- src/api/bundles.js
- src/api/domainkey.js
- src/api/index.js
- src/bundler/BundleGroup.js
- src/bundler/index.js
- src/index.js
- src/support/PathInfo.js
- src/support/cache.js
- src/support/domains.js
- src/support/util.js
- test/bundler/index.test.js
- test/dev/tools/import-bundles.js
- test/dev/tools/import-domainkeys-to-bq.js
- test/support/util.test.js
> fix: generate domainkeys for new domains

- src/api/bundles.js
- test/dev/tools/bq/index.js
- test/dev/tools/bq/sendquery.js
- test/dev/tools/import-bundles.js
- test/dev/tools/util.js
- tool improvements
- add min bundle weights
> various fixes

- src/bundler/virtual.js
- src/support/util.js
> fix: add cwvs to aggregates

- src/bundler/virtual.js
> fix: faster virtual rule

- src/bundler/BundleGroup.js
- src/bundler/virtual.js
- src/support/util.js
> fix: actually include cwv events

- src/support/domains.js
- test/api/domainkey.test.js
- test/bundler/index.test.js
- test/util.js
> fix: remove rq connection

- src/bundler/index.js
- src/support/storage.js
- test/bundler/index.test.js
- test/bundler/virtual.test.js
> optimizations

- src/api/orgs.js
- src/support/orgs.js
- test/api/orgs.test.js
> fix: delete org api

- src/api/bundles.js
- src/support/util.js
> fix: make downsampling deterministic

- .husky/pre-commit
- package.json
see https://github.com/adobe/helix-rum-bundler/actions/runs/10022986885/job/27703382001
and https://github.com/typicode/husky/issues/1472
> fix(deps): upgrade husky

- src/support/util.js
> fix: make fingerprintvalue include weight

- src/bundler/index.js
- src/bundler/virtual.js
- src/support/util.js
- src/types.d.ts
- test/bundler/virtual.test.js
- test/dev/tools/find-hash.js
add virtual rule to bundle `ref--site--org.(hlx|aem).(page|live)` into a virtual org domain:`{org}.aem.live`
> More virtuals

- .gitignore
- src/api/bundles.js
> fix: limit concurrency in apis

- src/api/bundles.js
- src/bundler/BundleGroup.js
- src/bundler/Manifest.js
- src/support/storage.js
> fix: use debug logs for chatty read/writes

- src/api/orgs.js
- src/support/PathInfo.js
- src/types.d.ts
- test/api/orgs.test.js
> fix: add helixorg link

- src/bundler/index.js
- test/dev/tools/util.js
> fix: add invocation id to lock meta

- src/bundler/index.js
- src/cloudflare.js
- src/index.js
- src/support/loop.js
- src/support/storage.js
- src/types.d.ts
- test/bundler/fixtures/event.json
- test/bundler/index.test.js
- test/cloudflare.test.js
- test/dev/tools/util.js
- test/index.test.js
configuration changes to go along with this:
- change `task` for bundler schedule to `bundle-rum`
- remove `bundle-rum-cloudflare` schedule
- add schedule with task `process-cloudflare-events`
> fix: transform cf events

- src/api/bundles.js
- src/api/domainkey.js
- src/support/authorization.js
- src/types.d.ts
- test/api/domainkey.test.js
- goes with fastly `v21-29`
todo:
> fix: add and handle identifiers

- src/api/bundles.js
- src/support/util.js
- test/dev/tools/wipe-aggregates.js
- test/support/util.test.js
- remove requirement to downsample into orders of magnitude, meaning weights can be any integer
- increase event limits
> feat: downsample less

- src/bundler/virtual.js
- test/bundler/virtual.test.js
> fix: cleanup unused virtual rules

- src/bundler/virtual.js
- src/support/util.js
- test/bundler/virtual.test.js
- test/dev/tools/find-hash.js
- test/support/util.test.js
> fix: weighted selection for all aggregate

- src/bundler/virtual.js
relates to https://github.com/adobe/helix-rum-collector/pull/448
Please ensure your pull request adheres to the following guidelines:
Thanks for contributing!
> feat: add commerce hostType

- src/api/bundles.js
- test/api/bundles.test.js
- test/util.js
until the bundling can be parallelized
> fix: cache all time ranges less aggressively
